#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the LVGL 9 Chinese bitmap font used by Senior Safety Card.

用法:
  python3 tools/gen_safety_font.py --font /path/to/SourceHanSansSC-Regular.otf

字符集: 16px 为 ASCII + GB2312 一级汉字(3755 字)；昵称使用的 24px
        为 ASCII + 完整 GB2312 汉字(6763 字，包含一级和二级字) + 扩展昵称字形
位深:   2bpp(4 级灰度) —— 中文小字比 1bpp 清晰得多,比 4bpp 省一半 flash
输出:   components/ui/presentation/src/lv_font_cn_<size>.c  (字体进 .rodata/flash,不占 DRAM)

换字体只需改 FONT_PATH(量产建议换开源字体,如思源黑体/文泉驿)。
"""
import argparse
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("缺少 Pillow: pip install pillow")

FONT_PATH = os.environ.get("SAFETY_FONT_PATH", "")
FALLBACK_FONT_PATH = FONT_PATH
BPP = 2
OUT_DIR = os.path.join(os.path.dirname(__file__), "../main")

# 表单正文会自然包含中文标点；它们不属于 GB2312 汉字区，必须显式加入。
COMMON_SYMBOLS = "，。！？：；、‘’“”（）【】《》…—·￥↑↓"

# GB2312/ASCII 之外、产品昵称中确认需要显示的姓名用字和符号。集中维护，
# 避免为了少量字形引入整个 GBK/CJK 字库而超过 ESP32-C3 的应用分区容量。
NICKNAME_EXTRA_CHARS = (
    "珺鍠雲飂鎛琭汎佈柷敔吥昇嗏燚溦彧燊吳垚榮拝楿髙。、～！（）°μ…″"
    "喆鋆韡烋烜璟旻祎姞飔玥瑄崝珅翬珹悅炘赟贇渱璠珮劼芃甦镕爔昪禤暢玶淏崟"
    "𤩽熺偲竑暐棨钖熇珽翀嫄宬湲湧嫚濛堃啟愷旸㛃倞玙杍翚桪昫昞樑纮澔梽頔"
    "姮冮顥晞沄屾祐锜瑨焜曈詝飏浛瑀栯橦妘競琎敭鹍镠禕乂荍珵嶒辀昳軻璘棫"
    "皛麥璕漘栢奡·，•′¯"
)
NICKNAME_FALLBACK_CHARS = "•¯𤩽"


def gb2312_hanzi(include_level2=False):
    """枚举 GB2312 汉字；可包含二级字(0xD8A1-0xF7FE)。"""
    chars = []
    hi_end = 0xF8 if include_level2 else 0xD8
    for hi in range(0xB0, hi_end):
        for lo in range(0xA1, 0xFF):
            try:
                ch = bytes([hi, lo]).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if len(ch) == 1 and 0x4E00 <= ord(ch) <= 0x9FA5:
                chars.append(ch)
    return chars


def nickname_hanzi():
    """返回 24px 昵称字体字符集（完整 GB2312 + 额外姓名用字/符号）。"""
    chars = gb2312_hanzi(include_level2=True)
    for ch in NICKNAME_EXTRA_CHARS:
        if ch not in chars:
            chars.append(ch)
    return chars


def split_sparse_cmap_chars(chars):
    """按 LVGL SPARSE_TINY 的 uint16_t 偏移范围拆分有序字符。"""
    groups = []
    for ch in chars:
        if not groups or ord(ch) - ord(groups[-1][0]) > 0xFFFF:
            groups.append([])
        groups[-1].append(ch)
    return groups


def pack_bits(vals, bpp):
    """按 bpp 把像素值打包成字节流(MSB first,末尾补 0)——LVGL fmt_txt 位图格式。"""
    out = bytearray()
    acc = nbits = 0
    for v in vals:
        acc = (acc << bpp) | (v & ((1 << bpp) - 1))
        nbits += bpp
        while nbits >= 8:
            nbits -= 8
            out.append((acc >> nbits) & 0xFF)
    if nbits:
        out.append((acc << (8 - nbits)) & 0xFF)
    return bytes(out)


def render_glyph(font, ch, ascent, bpp):
    """渲染一个字形,返回 (bitmap_bytes, box_w, box_h, ofs_x, ofs_y, adv_w)。"""
    adv_w = int(round(font.getlength(ch) * 16))       # LVGL adv_w 单位 = 1/16 px
    bbox = font.getbbox(ch)
    if bbox is None:
        return b"", 0, 0, 0, 0, adv_w
    x0, y0, x1, y1 = bbox
    w, h = x1 - x0, y1 - y0
    if w <= 0 or h <= 0:                              # 空格等无墨迹字形
        return b"", 0, 0, 0, 0, adv_w

    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
    shift = 8 - bpp
    vals = [p >> shift for p in img.getdata()]        # 255→3 (2bpp)
    return pack_bits(vals, bpp), w, h, x0, ascent - y1, adv_w


def gen(size, out_path, font_name):
    font = ImageFont.truetype(FONT_PATH, size)
    fallback_font = ImageFont.truetype(FALLBACK_FONT_PATH, size) if size == 24 else None
    ascent, descent = font.getmetrics()

    ascii_chars = [chr(c) for c in range(0x20, 0x7F)]         # 95 个
    # 昵称固定使用 24px 字体。仅为它加入 3008 个二级汉字，既覆盖阚、邴、郗、
    # 逯、仉、佘、亓、訾、琰、珩等姓名用字，也避免把 16px 字体同步膨胀。
    include_level2 = size == 24
    cjk_chars = nickname_hanzi() if include_level2 else gb2312_hanzi()
    for ch in COMMON_SYMBOLS:
        if ch not in cjk_chars:
            cjk_chars.append(ch)
    cjk_chars.sort(key=ord)
    all_chars = ascii_chars + cjk_chars

    bitmap = bytearray()
    dscs = [(0, 0, 0, 0, 0, 0)]                                # id 0 保留
    for ch in all_chars:
        if fallback_font and ch in NICKNAME_FALLBACK_CHARS:
            glyph_font = fallback_font
        else:
            glyph_font = font
        bm, bw, bh, ox, oy, aw = render_glyph(glyph_font, ch, ascent, BPP)
        dscs.append((len(bitmap), aw, bw, bh, ox, oy))
        bitmap += bm

    cjk_groups = split_sparse_cmap_chars(cjk_chars)
    ascii_gid_start = 1

    L = []
    L.append('// Generated by tools/gen_safety_font.py; do not edit manually.')
    L.append('// Source Han Sans SC is licensed under the SIL Open Font License 1.1.')
    L.append(f'// 字体:{os.path.basename(FONT_PATH)}  字号:{size}px  位深:{BPP}bpp')
    charset_name = 'GB2312 完整汉字（一级 + 二级）+ 扩展昵称字形' if include_level2 else 'GB2312 一级汉字'
    L.append(f'// 字符集:ASCII(0x20-0x7E) + {charset_name}({len(cjk_chars)} 字)')
    L.append('// 数据为 const,进 flash(.rodata),不占 DRAM。')
    L.append('#include "lvgl.h"')
    L.append('')
    L.append(f'#if LV_FONT_CN_{size}_ENABLE || 1')
    L.append('')
    L.append('static const uint8_t glyph_bitmap[] = {')
    for i in range(0, len(bitmap), 16):
        L.append('    ' + ''.join(f'0x{b:02X},' for b in bitmap[i:i + 16]))
    L.append('};')
    L.append('')
    L.append('static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {')
    for (bi, aw, bw, bh, ox, oy) in dscs:
        L.append(f'    {{.bitmap_index = {bi}, .adv_w = {aw}, .box_w = {bw}, '
                 f'.box_h = {bh}, .ofs_x = {ox}, .ofs_y = {oy}}},')
    L.append('};')
    L.append('')
    L.append('/*码位稀疏；按 uint16_t 偏移上限拆分 cmap。*/')
    for group_index, group in enumerate(cjk_groups):
        if len(group) == 1:
            continue
        group_start = ord(group[0])
        offs = [ord(ch) - group_start for ch in group]
        L.append(f'static const uint16_t unicode_list_cjk_{group_index}[] = {{')
        for i in range(0, len(offs), 12):
            L.append('    ' + ''.join(f'0x{o:04X}, ' for o in offs[i:i + 12]).rstrip())
        L.append('};')
        L.append('')
    L.append('static const lv_font_fmt_txt_cmap_t cmaps[] = {')
    L.append('    {')
    L.append(f'        .range_start = 32, .range_length = {len(ascii_chars)}, '
             f'.glyph_id_start = {ascii_gid_start},')
    L.append('        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,')
    L.append('        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY')
    L.append('    },')
    cjk_gid_start = 1 + len(ascii_chars)
    for group_index, group in enumerate(cjk_groups):
        group_start = ord(group[0])
        group_end = ord(group[-1])
        L.append('    {')
        L.append(f'        .range_start = {group_start}, .range_length = {group_end - group_start + 1}, '
                 f'.glyph_id_start = {cjk_gid_start},')
        if len(group) == 1:
            L.append('        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0,')
            L.append('        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY')
        else:
            L.append(f'        .unicode_list = unicode_list_cjk_{group_index}, .glyph_id_ofs_list = NULL, '
                     f'.list_length = {len(group)},')
            L.append('        .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY')
        cjk_gid_start += len(group)
        L.append('    },')
    L.append('};')
    L.append('')
    L.append('static const lv_font_fmt_txt_dsc_t font_dsc = {')
    L.append('    .glyph_bitmap = glyph_bitmap,')
    L.append('    .glyph_dsc = glyph_dsc,')
    L.append('    .cmaps = cmaps,')
    L.append('    .kern_dsc = NULL,')
    L.append('    .kern_scale = 0,')
    L.append(f'    .cmap_num = {1 + len(cjk_groups)},')
    L.append(f'    .bpp = {BPP},')
    L.append('    .kern_classes = 0,')
    L.append('    .bitmap_format = 0,')
    L.append('};')
    L.append('')
    L.append(f'const lv_font_t {font_name} = {{')
    L.append('    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,')
    L.append('    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,')
    L.append(f'    .line_height = {ascent + descent},')
    L.append(f'    .base_line = {descent},')
    L.append('    .subpx = LV_FONT_SUBPX_NONE,')
    L.append('    .underline_position = -2,')
    L.append('    .underline_thickness = 1,')
    L.append('    .dsc = &font_dsc,')
    L.append('    .fallback = NULL,')
    L.append('    .user_data = NULL,')
    L.append('};')
    L.append('')
    L.append('#endif')
    L.append('')

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"生成 {os.path.normpath(out_path)}  字形={len(dscs)-1} "
          f"位图={len(bitmap)/1024:.1f}KB 行高={ascent+descent} 基线={descent}")


def main():
    global FONT_PATH, FALLBACK_FONT_PATH
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=FONT_PATH,
                    help="Path to SourceHanSansSC-Regular.otf (or another OFL-compatible font)")
    ap.add_argument("--size", type=int, action="append", help="字号(可多次);默认 16 和 24")
    args = ap.parse_args()
    FONT_PATH = args.font
    FALLBACK_FONT_PATH = args.font
    sizes = args.size or [16]
    if not os.path.exists(FONT_PATH):
        sys.exit(f"找不到字体文件: {FONT_PATH}")
    os.makedirs(OUT_DIR, exist_ok=True)
    for s in sizes:
        gen(s, os.path.join(OUT_DIR, f"lv_font_cn_{s}.c"), f"lv_font_cn_{s}")


if __name__ == "__main__":
    main()
